server:
    port: 8304
spring:
    application:
        name: auth-service
    datasource:
        url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:5432/auth_db
        username: auth-service
        password: auth-service-01
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    flyway:
        locations: classpath:db/migration
        url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:5432/auth_db
        user: auth-service
        password: auth-service-01
    cloud:
        azure:
            servicebus:
                connection-string: ${CONNECTION_QUEUE_STRING}
                queue: user-auth
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8301/eureka
        fetch-registry: true
        register-with-eureka: true
    instance:
        hostname: localhost
jwt:
    secret: WvqWxVY0NuX469fNVMVT3YsJmLevE6Vk4TOwfwqhVOaiGYLE8jTtmmclg7Zm/LOAbRJKPq5SAzlWh0NI7Y01urMPvreS13eo89hb7YaDd7k=
    expiration: 604800

logging:
    level:
        org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator: debug
        org.hibernate.SQL: debug
        com.zaxxer.hikari: DEBUG
        org.hibernate.tool.schema: DEBUG
        org.hibernate.engine.jdbc.spi: DEBUG
        org.hibernate.type.descriptor.sql: TRACE
        org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentImpl: TRACE