server:
    port: 8304
spring:
    application:
        name: auth-service
    datasource:
        url: jdbc:postgresql://${DB_HOST:localhost}:5432/auth_db
        username: ${AUTH_SERVICE_USER:auth-service}
        password: ${AUTH_SERVICE_PASSWORD:auth-service-01}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    flyway:
        locations: classpath:db/migration
        url: jdbc:postgresql://${DB_HOST:localhost}:5432/auth_db
        user: ${AUTH_SERVICE_USER:auth-service}
        password: ${AUTH_SERVICE_PASSWORD:auth-service-01}
    cloud:
        azure:
            servicebus:
                connection-string: ${CONNECTION_TOPIC_STRING:Endpoint=sb://localhost/;SharedAccessKeyName=dev;SharedAccessKey=devKey}
eureka:
    client:
        service-url:
            defaultZone: http://${REGISTRY_HOST:localhost}:8301/eureka
        fetch-registry: true
        register-with-eureka: true
    instance:
        hostname: ${HOST_ADDR:localhost}
jwt:
    secret: ${TOKEN_SECRET:89c5c5074fe690774ce317014d8d37cfc3633231d2}
    expiration: 6048    00

logging:
    level:
        org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator: debug
        org.hibernate.SQL: debug
        com.zaxxer.hikari: DEBUG
        org.hibernate.tool.schema: DEBUG
        org.hibernate.engine.jdbc.spi: DEBUG
        org.hibernate.type.descriptor.sql: TRACE
        org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentImpl: TRACE