server:
    port: 8301
spring:
    application:
        name: registry-server
    zipkin:
        base-url: http://${ZIPKIN_HOST:localhost}:9411

eureka:
    client:
        fetch-registry: false
        register-with-eureka: false
        service-url:
            defaultZone: http://${REGISTRY_HOST}:8301/eureka/
    instance:
        hostname: ${REGISTRY_HOST:localhost}
    server:
        renewal-percent-threshold: 0.5
        renewal-threshold-update-interval-ms: 60000