apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: ecom
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: ecomsystem01.azurecr.io/payment-service
          ports:
            - containerPort: 8307
              name: http
          env:
            - name: REGISTRY_HOST
              value: "registry-server"
            - name: HOST_ADDR
              value: "payment-service"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_HOST
            - name: DATASOURCE_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_HOST
            - name: ID_SERVICE_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: PG_HOST_USER
            - name: ID_SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: PG_HOST_PASSWORD
            - name: PAYMENT_SERVICE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: PAYMENT_SERVICE_USERNAME
            - name: PAYMENT_SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: PAYMENT_SERVICE_PASSWORD
            - name: CONNECTION_TOPIC_STRING
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: CONNECTION_TOPIC_STRING
            - name: TMN_CODE
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: TMN_CODE
            - name: HASH_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: HASH_SECRET
            - name: VNPAY_CALL_BACK
              value: "https://dinhhuan.id.vn/payments/return-callback"
            - name: MOMO_PARTNER_CODE
              value: "MOMO"
            - name: MOMO_ACCESS_KEY
              value: "F8BBA842ECF85"
            - name: MOMO_SECRET_KEY
              value: "K951B6PE1waDMi640xX08PD3vg6EkVlz"
            - name: MOMO_RETURN_URL
              value: "https://dinhhuan.id.vn/payments/momo-callback"
            - name: MOMO_NOTIFY_URL
              value: "https://dinhhuan.id.vn/payments/momo-callback"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: ecom
  labels:
    app: order-service
spec:
  selector:
    app: order-service
  ports:
    - port: 8306
      targetPort: 8306
      protocol: TCP
      name: http
  type: ClusterIP