apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: ecom
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: ecomsystem01.azurecr.io/product-service
          ports:
            - containerPort: 8305
              name: http
          env:
            - name: REGISTRY_HOST
              value: "registry-server"
            - name: HOST_ADDR
              value: "product-service"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_HOST
            - name: DATASOURCE_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_HOST
            - name: ID_SERVICE_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: PG_HOST_USER
            - name: ID_SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: PG_HOST_PASSWORD
            - name: PRODUCT_SERVICE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: PRODUCT_SERVICE_USERNAME
            - name: PRODUCT_SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: PRODUCT_SERVICE_PASSWORD
            - name: CONNECTION_TOPIC_STRING
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: CONNECTION_TOPIC_STRING
            - name: STORAGE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: STORAGE_ACCOUNT_KEY
            - name: STORAGE_ACCOUNT_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: STORAGE_ACCOUNT_NAME
            - name: STORAGE_CONTAINER_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: STORAGE_CONTAINER_NAME
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: ecom
  labels:
    app: product-service
spec:
  selector:
    app: product-service
  ports:
    - port: 8305
      targetPort: 8305
      protocol: TCP
      name: http
  type: ClusterIP