server:
    port: 8302
spring:
    application:
        name: user-service
    datasource:
        url: jdbc:postgresql://localhost:5432/user_db
        username: usr-service
        password: user-service-01
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: validate
    flyway:
        locations: classpath:db/migration
        url: jdbc:postgresql://localhost:5432/user_db
        user: usr-service
        password: user-service-01
    cloud:
        azure:
            servicebus:
                connection-string: ${CONNECTION_STRING}
        function:
            definition: consumerRegistration
        stream:
            bindings:
                consumerRegistration-in-0:
                    destination: user-auth
            servicebus:
                bindings:
                    consumerRegistration-in-0:
                        consumer:
                            auto-complete: true
                            max-concurrent-calls: 5
                            prefetch-count: 10

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8301/eureka
        fetch-registry: true
        register-with-eureka: true
    instance:
        hostname: localhost
logging:
    level:
        org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator: debug
        org.hibernate.SQL: debug
        com.zaxxer.hikari: DEBUG
        org.hibernate.tool.schema: DEBUG
        org.hibernate.engine.jdbc.spi: DEBUG
        org.hibernate.type.descriptor.sql: TRACE
        org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentImpl: TRACE


