server:
    port: 8302
spring:
    application:
        name: user-service
    datasource:
        url: jdbc:postgresql://${DB_HOST:localhost}:5432/user_db
        username: ${USR_SERVICE_USERNAME:usr-service}
        password: ${USR_SERVICE_PASSWORD:user-service-01}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: validate
    flyway:
        locations: classpath:db/migration
        url: jdbc:postgresql://${DB_HOST:localhost}:5432/user_db
        user: ${USR_SERVICE_USERNAME:usr-service}
        password: ${USR_SERVICE_PASSWORD:user-service-01}
    cloud:
        function:
            definition: consumerRegistration
        azure:
            servicebus:
                connection-string: ${CONNECTION_TOPIC_STRING:Endpoint=sb://localhost/;SharedAccessKeyName=dev;SharedAccessKey=devKey}
        stream:
            bindings:
                consumerRegistration-in-0:
                    destination: user-topic
                    group: user-service-sub
            servicebus:
                bindings:
                    consumerRegistration-in-0:
                        consumer:
                            auto-complete: true
                            max-concurrent-calls: 5
                            prefetch-count: 10

eureka:
    client:
        service-url:
            defaultZone: http://${REGISTRY_HOST:localhost}:8301/eureka
        fetch-registry: true
        register-with-eureka: true
    instance:
        hostname: ${HOST_ADDR:localhost}
logging:
    level:
        org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator: debug
        org.hibernate.SQL: debug
        com.zaxxer.hikari: DEBUG
        org.hibernate.tool.schema: DEBUG
        org.hibernate.engine.jdbc.spi: DEBUG
        org.hibernate.type.descriptor.sql: TRACE
        org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentImpl: TRACE


