server:
  port: 8306

spring:
    application:
        name: order-service
    datasource:
        url: jdbc:postgresql://localhost:5432/order_db
        username: order-service
        password: order-service-01
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    flyway:
        locations: classpath:db/migration
        url: jdbc:postgresql://localhost:5432/order_db
        user: order-service
        password: order-service-01
    cloud:
        function:
            definition: consumerRegistration
        azure:
            servicebus:
                connection-string: ${CONNECTION_QUEUE_STRING}
        stream:
            bindings:
                consumerRegistration-in-0:
                    destination: user-auth
            servicebus:
                bindings:
                    consumerRegistration-in-0:
                        consumer:
                            auto-complete: true
                            max-concurrent-calls: 5
                            prefetch-count: 10
